# Configuracoes do Quarkus
quarkus.http.port=8081

# Configuracoes do RabbitMQ
rabbitmq.host=localhost
rabbitmq.port=5672
rabbitmq.queue.name=osinfo
rabbitmq.username=guest
rabbitmq.password=guest

# Configuracoes do MinIO
quarkus.minio.url=http://localhost:9002
quarkus.minio.access-key=minioadmin
quarkus.minio.secret-key=minioadmin
minio.bucket-name=osinfo

# Evitar a criacao de novos containers
quarkus.devservices.enabled=false

# quarkus.rabbitmq.port=5672 # Porta padrao, nao precisa ser especificada
#quarkus.rabbitmq.virtual-host=/
#mp.messaging.outgoing.osinfo-out.connector=smallrye-rabbitmq
#mp.messaging.outgoing.osinfo-out.host=rabbitmq
#mp.messaging.outgoing.osinfo-out.username=guest
#mp.messaging.outgoing.osinfo-out.password=guest
#mp.messaging.outgoing.osinfo-out.address=osinfo # Nome da fila/exchange
#quarkus.log.category."io.quarkus.rabbitmq".level=DEBUG

# Configuracoes do MinIO (Container Docker)
#minio.access.key=minioadmin
#minio.secret.key=minioadmin
#minio.url=http://localhost:9002 # Porta 9002 mapeada para 9000 no container
#minio.bucket.name=seu-bucket

# Outras configuracoes (opcional)
#quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
#quarkus.log.level=INFO
